## Intro
Video Link: https://www.youtube.com/watch?v=KNAWp2S3w94

In [1]:
# https://www.youtube.com/watch?v=KNAWp2S3w94

import tensorflow as tf
import numpy as np

2023-02-27 23:52:07.120022: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1]),
])

2023-02-27 23:52:11.631759: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(
    optimizer="sgd",
    loss="mean_squared_error",
)

In [5]:
x = np.array([-1, 0, 1, 2, 3, 4], dtype=float)
y = np.array([-3, -1, 1, 3, 5, 7], dtype=float)

print(x)
print(y)

[-1.  0.  1.  2.  3.  4.]
[-3. -1.  1.  3.  5.  7.]


In [6]:
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 0s 319ms/step - loss: 2.6546
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 2.2405
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 1.9116
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 1.6497
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 1.4407
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 1.2734
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 1.1388
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 1.0302
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.9419
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.8698
Epoch 11/100
1/1 [==============================] - 0s 4ms/step - loss: 0.8104
Epoch 12/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7611
Epoch 13/100
1/1 [==============================] - 0s 6ms/

In [7]:
model.predict([10.0])

1/1 [==============================] - 0s 100ms/step


array([[18.072498]], dtype=float32)

## Fashion MNIST
Video Link: https://youtu.be/bemDFpNooA8

In [20]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [21]:
train_images.shape

(60000, 28, 28)

In [22]:
train_labels.shape

(60000,)

In [23]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax),
])

In [24]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 128)               100480    
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

In [26]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 3.1167 - accuracy: 0.6678
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.6969 - accuracy: 0.7577
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5941 - accuracy: 0.7940
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5375 - accuracy: 0.8103
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5314 - accuracy: 0.8161


In [28]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_acc:.4f}")

313/313 [==============================] - 0s 1ms/step - loss: 0.5596 - accuracy: 0.8174
Test Loss: 0.5596, Test Accuracy: 0.8174


In [38]:
sample_image = train_images[0]

pred = model.predict(train_images[0].reshape(1, 28, 28))

print(f"Prediction Result: {np.argmax(pred)}")
print(f"Answer: {train_labels[0]}")

1/1 [==============================] - 0s 19ms/step
Prediction Result: 9
Answer: 9
