In [2]:
import tensorflow as tf

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense


batch_size = 32

model = Sequential([
    Embedding(batch_size, 64, input_length=30),
    Flatten(),
    Dense(3, activation="relu"),
])

2023-02-25 13:04:32.384800: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
model

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 30, 64)            2048      
                                                                 
 flatten (Flatten)           (None, 1920)              0         
                                                                 
 dense (Dense)               (None, 3)                 5763      
                                                                 
Total params: 7,811
Trainable params: 7,811
Non-trainable params: 0
_________________________________________________________________


In [14]:
tf.random.uniform(shape=[128, 30])

<tf.Tensor: shape=(128, 30), dtype=float32, numpy=
array([[0.8961592 , 0.18652117, 0.00308526, ..., 0.3928566 , 0.894282  ,
        0.15054286],
       [0.85607374, 0.26575303, 0.62575126, ..., 0.7796391 , 0.4155941 ,
        0.64770055],
       [0.55605483, 0.32109237, 0.78327537, ..., 0.94200635, 0.25302327,
        0.01880991],
       ...,
       [0.65683067, 0.12700498, 0.31996942, ..., 0.96840215, 0.05286002,
        0.3504702 ],
       [0.54818857, 0.10560656, 0.5492163 , ..., 0.03055632, 0.17665696,
        0.24453807],
       [0.5661417 , 0.07087457, 0.909546  , ..., 0.1905855 , 0.40099382,
        0.768927  ]], dtype=float32)>

In [15]:
sample_tensor = tf.random.uniform(shape=[128, 30])

In [16]:
model(sample_tensor)

<tf.Tensor: shape=(128, 3), dtype=float32, numpy=
array([[0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
       [0.        , 0.02592088, 0.01417256],
     

In [43]:
sample_tensor = tf.random.uniform(shape=[128, 30])
layer_1 = Embedding(32, 64, input_length=30)
layer_2 = Flatten()
layer_3 = Dense(3, activation="relu")
x = layer_1(sample_tensor)
y = layer_2(x)
z = layer_3(y)

print(sample_tensor.shape)
print(x.shape)
print(y.shape)
print(z.shape)

(128, 30)
(128, 30, 64)
(128, 1920)
(128, 3)


In [19]:
layer_1 = Embedding(32, 64, input_length=30)
layer_2 = Flatten()
layer_3 = Dense(3, activation="relu")

In [20]:
layer_1(sample_tensor)

<tf.Tensor: shape=(128, 30, 64), dtype=float32, numpy=
array([[[-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        ...,
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498]],

       [[-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        ...,

In [21]:
x = layer_1(sample_tensor)
y = layer_2(x)
z = layer_3(y)

In [26]:
x

<tf.Tensor: shape=(128, 30, 64), dtype=float32, numpy=
array([[[-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        ...,
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498]],

       [[-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        [-0.02036272, -0.0237268 ,  0.00631499, ..., -0.02310616,
         -0.02643397,  0.01442498],
        ...,

In [27]:
import tensorflow as tf

# Define the input sequence as a list of integers
input_sequence = [1, 2, 3, 4, 5]

# Define the vocabulary size and embedding dimension
vocab_size = 10
embedding_dim = 4

# Create the Embedding layer
embedding_layer = tf.keras.layers.Embedding(input_dim=vocab_size,
                                             output_dim=embedding_dim,
                                             input_length=len(input_sequence))

# Convert the input sequence into a tensor
input_tensor = tf.constant([input_sequence])

# Apply the Embedding layer to the input tensor
output_tensor = embedding_layer(input_tensor)

# Print the output tensor
print(output_tensor)


tf.Tensor(
[[[-0.03418969  0.04032305 -0.03208804 -0.01132747]
  [ 0.00268213  0.03741105  0.04512442  0.03014264]
  [ 0.03664098  0.01156452  0.02550048 -0.00318028]
  [-0.00337983 -0.02752945  0.02263576 -0.01412369]
  [ 0.01858387  0.00604148  0.03327641 -0.02246153]]], shape=(1, 5, 4), dtype=float32)


In [28]:
input_tensor.shape

TensorShape([1, 5])

In [31]:
Sequential([embedding_layer]).summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 5, 4)              40        
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [32]:
import tensorflow as tf

# Define the input sequence as a list of integers
input_sequence = [1, 2, 3, 4, 5]

# Define the vocabulary size and embedding dimension
vocab_size = 20
embedding_dim = 4

# Create the Embedding layer
embedding_layer = tf.keras.layers.Embedding(input_dim=vocab_size,
                                             output_dim=embedding_dim,
                                             input_length=len(input_sequence))

# Convert the input sequence into a tensor
input_tensor = tf.constant([input_sequence])

# Apply the Embedding layer to the input tensor
output_tensor = embedding_layer(input_tensor)

# Print the output tensor
print(output_tensor)

Sequential([embedding_layer]).summary()

tf.Tensor(
[[[-0.01662654  0.02190778 -0.01608838  0.02065922]
  [-0.04036766 -0.04143571  0.03835041  0.02209977]
  [-0.04490414  0.00259271  0.04704073  0.0349595 ]
  [ 0.03535949  0.01210357  0.02231849 -0.04862317]
  [-0.0451902   0.0126653  -0.04824703  0.00698972]]], shape=(1, 5, 4), dtype=float32)
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 5, 4)              80        
                                                                 
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [46]:
import tensorflow as tf

# Define the input sequence as a list of integers
input_sequence = [1, 2, 3, 4, 5]

# Define the vocabulary size and embedding dimension
vocab_size = 6
embedding_dim = 4

# Create the Embedding layer
embedding_layer = tf.keras.layers.Embedding(input_dim=vocab_size,
                                             output_dim=embedding_dim,
                                             input_length=len(input_sequence))

# Convert the input sequence into a tensor
input_tensor = tf.constant([input_sequence])

# Apply the Embedding layer to the input tensor
output_tensor = embedding_layer(input_tensor)

# Print the output tensor
print(output_tensor)

Sequential([embedding_layer]).summary()

tf.Tensor(
[[[ 0.02090628 -0.00707681  0.01176493 -0.04236705]
  [-0.04514579  0.03301262 -0.04939482 -0.03017534]
  [-0.0364027  -0.03103849  0.00979775 -0.0412675 ]
  [ 0.01443014  0.03965732  0.04189073  0.04499013]
  [ 0.00147795 -0.00783066 -0.01002204 -0.02299225]]], shape=(1, 5, 4), dtype=float32)
Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_14 (Embedding)    (None, 5, 4)              24        
                                                                 
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [40]:
import tensorflow as tf

# Define the input sequence as a list of integers
input_sequence = [[1, 2, 3, 4, 5], [6,7,8,9,10]]

# Define the vocabulary size and embedding dimension
vocab_size = 20
embedding_dim = 4

# Create the Embedding layer
embedding_layer = tf.keras.layers.Embedding(input_dim=vocab_size,
                                             output_dim=embedding_dim,
                                             input_length=len(input_sequence[0]))

# Convert the input sequence into a tensor
input_tensor = tf.constant(input_sequence)

# Apply the Embedding layer to the input tensor
output_tensor = embedding_layer(input_tensor)

# Print the output tensor
print(output_tensor)

Sequential([embedding_layer]).summary()

tf.Tensor(
[[[-0.0010475  -0.0382571  -0.03895509 -0.01551219]
  [-0.01688478  0.01388098  0.03693408 -0.00888158]
  [-0.01171356  0.01665914 -0.03428346  0.03826653]
  [-0.04147266 -0.01506538 -0.03454428 -0.00795183]
  [ 0.02516628  0.04580224 -0.01796976  0.01137583]]

 [[ 0.01933844 -0.02477287 -0.02668176  0.00887012]
  [-0.04722112 -0.02435671  0.00215621  0.02494004]
  [ 0.03064785  0.02114118 -0.02324005 -0.0446303 ]
  [-0.00400505  0.00574537 -0.02762654 -0.00503178]
  [-0.04745935 -0.00196664  0.00296607 -0.04356611]]], shape=(2, 5, 4), dtype=float32)
Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_10 (Embedding)    (None, 5, 4)              80        
                                                                 
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [42]:
import numpy as np

np.random.randint(1000)

19

In [47]:
from tensorflow.keras.layers import Input

a = tf.constant([1, 2, 3, 4, 5])

input_layer = Input(shape=(5, ))

In [49]:
embedding_layer = input_layer

<KerasTensor: shape=(None, 5) dtype=float32 (created by layer 'input_1')>

In [50]:
import tensorflow as tf

# Define the shape of the input tensor
input_shape = (32,)

# Create the Input layer
input_layer = tf.keras.layers.Input(shape=input_shape, dtype=tf.float32)

# Create another layer that takes the input layer as input
hidden_layer = tf.keras.layers.Dense(units=64, activation='relu')(input_layer)

# Create the model by specifying the input and output layers
model = tf.keras.Model(inputs=input_layer, outputs=hidden_layer)

# Print the model summary
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_4 (Dense)             (None, 64)                2112      
                                                                 
Total params: 2,112
Trainable params: 2,112
Non-trainable params: 0
_________________________________________________________________


In [52]:
import tensorflow as tf

# Define the shape of the input tensor
input_shape = (32,)

# Create the Input layer
input_layer = tf.keras.layers.Input(shape=input_shape, dtype=tf.float32)

# Create another layer that takes the input layer as input
hidden_layer = tf.keras.layers.Dense(units=64, activation='relu')(input_layer)

# Create the model by specifying the input and output layers
model = tf.keras.Model(inputs=input_layer, outputs=hidden_layer)

# Print the model summary
model.summary()




Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_5 (Dense)             (None, 64)                2112      
                                                                 
Total params: 2,112
Trainable params: 2,112
Non-trainable params: 0
_________________________________________________________________


In [63]:
sample_tensor = tf.random.uniform(shape=[8, 32])

In [64]:
sample_tensor

<tf.Tensor: shape=(8, 32), dtype=float32, numpy=
array([[0.46945286, 0.03017509, 0.7259394 , 0.67181575, 0.27654254,
        0.9235605 , 0.4704144 , 0.95845866, 0.61214495, 0.4619323 ,
        0.13269877, 0.41948402, 0.03550673, 0.09371161, 0.39704573,
        0.47702658, 0.7882478 , 0.44684517, 0.96381545, 0.22317386,
        0.48420715, 0.84791195, 0.6141523 , 0.48651338, 0.17182434,
        0.96939397, 0.7418438 , 0.3506732 , 0.7388313 , 0.6904324 ,
        0.03845024, 0.8472487 ],
       [0.01249492, 0.28553033, 0.2286756 , 0.02653444, 0.5106282 ,
        0.67817473, 0.03488922, 0.1829822 , 0.2301122 , 0.7975955 ,
        0.95897543, 0.7211133 , 0.56337297, 0.64294016, 0.7929212 ,
        0.2393992 , 0.286366  , 0.65253425, 0.3779497 , 0.42921388,
        0.97239196, 0.9727074 , 0.2351495 , 0.3723421 , 0.21749103,
        0.8454287 , 0.09347403, 0.09907067, 0.18151736, 0.3659029 ,
        0.57383704, 0.82786894],
       [0.9674777 , 0.65574443, 0.74517643, 0.2766713 , 0.2562008 ,
 

In [65]:
model(sample_tensor)

<tf.Tensor: shape=(8, 64), dtype=float32, numpy=
array([[0.46018174, 0.04378627, 0.        , 0.        , 0.        ,
        0.42299438, 0.34523797, 0.        , 0.        , 0.12637489,
        0.        , 0.        , 0.        , 0.41921455, 0.        ,
        0.2914696 , 0.5749398 , 0.        , 0.77925515, 0.17308937,
        0.40170705, 0.06398591, 0.        , 0.63443774, 0.6560203 ,
        0.21986024, 0.3344061 , 0.4382151 , 0.21859968, 0.        ,
        0.        , 0.57530755, 0.        , 0.        , 0.5708516 ,
        0.1341946 , 0.3219872 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40437174, 0.        , 0.        ,
        0.44575614, 0.2270598 , 0.18034655, 1.0233651 , 0.17806147,
        0.        , 0.08093295, 0.6279463 , 0.02774907, 0.14967503,
        0.29047564, 0.        , 0.08493026, 0.18763764, 0.        ,
        0.        , 0.38196874, 0.13211797, 0.16025399],
       [0.        , 0.2411018 , 0.        , 0.11416762, 0.        ,
        0.

In [59]:
input_layer(sample_tensor)

TypeError: 'KerasTensor' object is not callable